site_name: Azure Active Directory for Linux
copyright: Copyright &copy; 2022 Azure Active Directory for Linux

repo_url: https://github.com/aad-for-linux/aad-for-linux

theme:
  logo: assets/logo/full_color.svg
  favicon: assets/favicon.svg
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/aad-for-linux/community

extra_css:
  - stylesheets/extra.css

